# Basic Site Settings
locale                   : "en-US"
title                    : "Arun Roy"
title_separator          : "-"
name                     : &name "Arun Roy"
description              : "Post Doctoral Fellow at the Indian Institute of Astrophysics, Bangalore. Specializing in optical and infrared studies of Herbig Ae/Be stars, with extensive research and publications in astrophysics."
url                      : https://arunroyon.github.io
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "arunroyon/"

# Navigation Menu (new)
menu:
  - title: "Home"
    url: "/"
  - title: "CV"
    url: "/cv/"
  - title: "Publications"
    url: "/publications/"
  - title: "Talks"
    url: "/talks/"
  - title: "Teaching"
    url: "/teaching/"

# Site Author - The following control what appears as part of the author content on the side bar.
author:
  avatar           : "profile.JPG"
  name             : "Arun Roy"
  pronouns         : 
  bio              : "Arun Roy is a Post Doctoral Fellow at the Indian Institute of Astrophysics, Bangalore, India. He earned his PhD in Physics from CHRIST (Deemed to be University), specializing in the optical and infrared studies of Herbig Ae/Be stars. His work on young stellar objects, emission-line stars, and circumstellar environments has been published in leading astronomy journals. He actively presents at international conferences and has received several awards and travel grants."
  location         : "Bangalore, India"
  employer         : "Indian Institute of Astrophysics, Bangalore"
  uri              : 
  email            : "arun.roy@iiap.res.in"

  # Academic websites
  arxiv            : 
  googlescholar    : "https://scholar.google.com/citations?user=5wyKyKgAAAAJ&hl=en"
  impactstory      : 
  orcid            : "https://orcid.org/0000-0002-4999-2990"
  pubmed           : "https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  researchgate     : 

  # Repositories and software development
  bitbucket        : 
  codepen          : 
  dribbble         : 
  github           : "arunroyon"
  kaggle           : 
  stackoverflow    : 

  # Social media
  bluesky          : "bsky.app"
  facebook         : 
  flickr           : 
  foursquare       : 
  goodreads        : 
  google_plus      : 
  keybase          : 
  instagram        : 
  lastfm           : 
  linkedin         : 
  mastodon         : 
  medium           : 
  pinterest        : 
  soundcloud       : 
  steam            : 
  telegram         : 
  tumblr           : 
  twitter          : "UniofOxford"
  vine             : 
  weibo            : 
  wikipedia        : 
  xing             : 
  youtube          : 
  zhihu            : 

# Site Settings
teaser                   : 
breadcrumbs              : false
words_per_minute         : 160
future                   : true
read_more                : "disabled"
talkmap_link             : false
comments:
  provider               : 
  disqus:
    shortname            :
  discourse:
    server               :
  facebook:
    appid                :
    num_posts            :
    colorscheme          :
staticman:
  allowedFields          : ['name', 'email', 'url', 'message']
  branch                 : "gh-pages"
  commitMessage          : "New comment."
  filename               : comment-{@timestamp}
  format                 : "yml"
  moderation             : true
  path                   : "_data/comments/{options.slug}"
  requiredFields         : ['name', 'email', 'message']
  transforms:
    email                : "md5"
  generatedFields:
    date:
      type               : "date"
      options:
        format           : "iso8601"
atom_feed:
  hide                   : false
  path                   :

# SEO Related
google_site_verification :
bing_site_verification   :
alexa_site_verification  :
yandex_site_verification :

# Social Sharing
twitter:
  username               : &twitter
facebook:
  username               :
  app_id                 :
  publisher              :
og_image                 : 
social:
  type                   :
  name                   :
  links:

# Analytics
analytics:
  provider               : "google-universal"
  google:
    tracking_id          :

# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
  publications:
    output: true
    permalink: /:collection/:path/
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  cv:                      # new collection for CV details
    output: true
    permalink: /cv/:path/

# Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
  - scope:                # default settings for CV pages
      path: ""
      type: cv
    values:
      layout: single
      author_profile: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed

# Outputting
permalink: /:categories/:title/
timezone: America/Los_Angeles

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-redirect-from
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
